# Generated by Django 6.1.1 on 2026-09-26 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0003_documentqualityanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_count',
            field=models.IntegerField(default=0, help_text='Number of cases assigned for review'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='Identity Screening Unit', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('REVIEWER', 'Forensic Reviewer / Officer'), ('USER', 'Standard Applicant / User')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Detailed forensic observations and review rationale')),
                ('recommended_action', models.CharField(choices=[('APPROVE', 'Recommend Approval / Cleared'), ('REJECT', 'Recommend Rejection / Anomaly Confirmed'), ('FURTHER_REVIEW', 'Request Secondary In-Person Review')], default='FURTHER_REVIEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_notes', to='documents.document')),
            ],
            options={
                'verbose_name': 'Review Note',
                'verbose_name_plural': 'Review Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
