# Generated by Django 6.1.1 on 2026-09-26 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_format', models.CharField(choices=[('PDF', 'PDF Dossier'), ('JSON', 'JSON Machine-Readable'), ('CSV', 'CSV Export')], default='PDF', max_length=10)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='documents.document')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Report',
                'verbose_name_plural': 'Verification Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
