# Generated by Django 6.1.1 on 2026-09-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Field identifier (e.g., name, id_number, dob, address, issue_date)', max_length=100)),
                ('field_value', models.TextField(blank=True, help_text='Normalized textual value extracted from the document')),
                ('confidence', models.FloatField(default=0.0, help_text='OCR extraction confidence percentage (0.0 to 100.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='documents.document')),
            ],
            options={
                'verbose_name': 'Extracted Field',
                'verbose_name_plural': 'Extracted Fields',
                'ordering': ['document', 'field_name'],
            },
        ),
    ]
