# Generated by Django 6.1.1 on 2026-09-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_selfie_file_document_selfie_hash_and_more'),
        ('ocr_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedfield',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='Field-level extraction confidence (0.0 to 1.0)'),
        ),
        migrations.AlterField(
            model_name='extractedfield',
            name='field_name',
            field=models.CharField(help_text='Field identifier (e.g., name, date_of_birth, document_number, address, gender, issue_date, expiry_date, document_type)', max_length=100),
        ),
        migrations.CreateModel(
            name='OCRAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, help_text='Raw unformatted text transcribed from the document')),
                ('overall_confidence', models.FloatField(default=0.0, help_text='Average OCR token recognition confidence score (0.0 to 1.0)')),
                ('engine_used', models.CharField(default='PaddleOCR', help_text='OCR engine backend used for execution', max_length=50)),
                ('quality_metrics', models.JSONField(blank=True, default=dict, help_text='Sharpness, contrast, brightness, blur assessment')),
                ('deskew_angle', models.FloatField(default=0.0, help_text='Detected and corrected skew angle in degrees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_analysis', to='documents.document')),
            ],
            options={
                'verbose_name': 'OCR Analysis Record',
                'verbose_name_plural': 'OCR Analysis Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
