# Generated by Django 6.1.1 on 2026-09-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk_score', models.FloatField(default=0.0, help_text='Aggregated risk index from 0.0 (clean) to 100.0 (high risk)')),
                ('risk_category', models.CharField(choices=[('LOW_RISK', 'Low Risk - Likely Authentic'), ('MODERATE_RISK', 'Moderate Risk - Flagged Signals'), ('HIGH_RISK', 'High Risk - High Probability Anomaly'), ('SUSPICIOUS_MANUAL_REVIEW', 'Suspicious - Officer Review Mandatory')], default='LOW_RISK', max_length=40)),
                ('ocr_score', models.FloatField(default=0.0, help_text='Text readability, format consistency, and checksum verification score (0.0 to 100.0)')),
                ('face_score', models.FloatField(default=0.0, help_text='Biometric confidence and facial match score (0.0 to 100.0)')),
                ('tamper_score', models.FloatField(default=0.0, help_text='Digital forensics integrity score (0.0 to 100.0, higher means cleaner image)')),
                ('consistency_score', models.FloatField(default=0.0, help_text='Logical validation score (DOB vs age, ID regex format, layout geometry)')),
                ('explanation', models.TextField(blank=True, help_text='Plain-language explainable AI audit summary of factors leading to the risk evaluation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_result', to='documents.document')),
            ],
            options={
                'verbose_name': 'Verification Result',
                'verbose_name_plural': 'Verification Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
