# Generated by Django 6.1.1 on 2026-09-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentqualityanalysis'),
        ('identity_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityConsistencyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_match', models.BooleanField(default=False, help_text='Whether normalized name comparison satisfies fuzzy matching threshold')),
                ('dob_match', models.BooleanField(default=False, help_text='Whether normalized date of birth matches')),
                ('document_number_match', models.BooleanField(default=False, help_text='Whether document identification number format and value are consistent')),
                ('address_match', models.BooleanField(default=False, help_text='Whether normalized address components match')),
                ('gender_match', models.BooleanField(default=True, help_text='Whether gender is consistent or unspecified')),
                ('consistency_score', models.IntegerField(default=0, help_text='Composite cross-field consistency score (0 to 100)')),
                ('status', models.CharField(choices=[('CONSISTENT', 'Consistent / Matched'), ('MANUAL_REVIEW', 'Manual Review Recommended'), ('DISCREPANCY', 'Field Discrepancies Detected')], default='MANUAL_REVIEW', max_length=30)),
                ('field_details', models.JSONField(blank=True, default=dict, help_text='Detailed field-by-field raw vs normalized values and similarity metrics')),
                ('signals', models.JSONField(blank=True, default=list, help_text='Forensic signals and discrepancy notes')),
                ('checklist', models.JSONField(blank=True, default=list, help_text="Checklist items (e.g. '✓ Name matched', '⚠ Address mismatch')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_check', to='documents.document')),
            ],
            options={
                'verbose_name': 'Identity Consistency Check',
                'verbose_name_plural': 'Identity Consistency Checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
