# Generated by Django 6.1.1 on 2026-09-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamperAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tampering_probability', models.FloatField(default=0.0, help_text='Calculated probability of digital manipulation (0.0 to 100.0)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (Original/Clean)'), ('MEDIUM', 'Medium Risk (Minor Compression Anomalies)'), ('HIGH', 'High Risk (Suspicious Pixel Splicing)'), ('CRITICAL', 'Critical (Definite Digital Forgery Indicators)')], default='LOW', max_length=20)),
                ('suspicious_regions', models.JSONField(blank=True, default=list, help_text='Bounding boxes and pixel coordinates of detected anomalous zones')),
                ('signals', models.JSONField(blank=True, default=dict, help_text='Forensic signals including ELA variance, metadata tags, compression noise, font mismatch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamper_analyses', to='documents.document')),
            ],
            options={
                'verbose_name': 'Tamper Analysis',
                'verbose_name_plural': 'Tamper Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
