# Generated by Django 6.1.1 on 2026-09-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentqualityanalysis'),
        ('tamper_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamperanalysis',
            name='annotated_image',
            field=models.CharField(blank=True, help_text='Relative media path to annotated forensic heatmap / bounding box visualization', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tamperanalysis',
            name='ela_image',
            field=models.CharField(blank=True, help_text='Relative media path to Error Level Analysis difference image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tamperanalysis',
            name='metadata_findings',
            field=models.JSONField(blank=True, default=dict, help_text='Findings from EXIF, software tag, and intake metadata inspection'),
        ),
        migrations.AddField(
            model_name='tamperanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tamperanalysis',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tamper_analysis', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='tamperanalysis',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk (Clean / Consistent)'), ('MODERATE', 'Moderate Risk (Minor Anomalies Detected)'), ('HIGH', 'High Risk (Suspicious Tampering Signals)')], default='LOW', help_text='Risk level categorization (LOW, MODERATE, HIGH)', max_length=20),
        ),
        migrations.AlterField(
            model_name='tamperanalysis',
            name='signals',
            field=models.JSONField(blank=True, default=list, help_text='List of explainable forensic signals / defect indicators identified'),
        ),
        migrations.AlterField(
            model_name='tamperanalysis',
            name='tampering_probability',
            field=models.FloatField(default=0.0, help_text='Calculated probability of digital manipulation (0.00 to 1.00)'),
        ),
    ]
