# Generated by Django 6.1.1 on 2026-09-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0, help_text='Cosine similarity score (0.0 to 1.0 or percentage)')),
                ('confidence', models.FloatField(default=0.0, help_text='Detection and alignment confidence (0.0 to 100.0)')),
                ('match_status', models.CharField(choices=[('MATCHED', 'Face Match Confirmed'), ('MISMATCH', 'Face Mismatch / Discrepancy'), ('NOT_DETECTED', 'No Face Detected in Document'), ('INCONCLUSIVE', 'Inconclusive / Low Quality Image')], default='INCONCLUSIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verifications', to='documents.document')),
            ],
            options={
                'verbose_name': 'Face Verification Result',
                'verbose_name_plural': 'Face Verification Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
