# Generated by Django 6.1.1 on 2026-09-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentqualityanalysis'),
        ('face_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverification',
            name='document_face_crop',
            field=models.CharField(blank=True, help_text='Relative media path to extracted document face crop', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='document_face_detected',
            field=models.BooleanField(default=False, help_text='Whether exactly one usable face was detected in the identity document'),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='document_faces_count',
            field=models.IntegerField(default=0, help_text='Total number of face instances detected in the identity document'),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='face_quality_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed quality metrics for document and selfie face crops'),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='issues',
            field=models.JSONField(blank=True, default=list, help_text='List of issues, defects, or warning flags identified during face analysis'),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='selfie_face_crop',
            field=models.CharField(blank=True, help_text='Relative media path to extracted selfie face crop', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='selfie_face_detected',
            field=models.BooleanField(default=False, help_text='Whether a usable face was detected in the applicant selfie'),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='selfie_faces_count',
            field=models.IntegerField(default=0, help_text='Total number of face instances detected in the applicant selfie'),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='threshold_used',
            field=models.FloatField(default=0.7, help_text='Match threshold applied for this verification decision'),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='Overall biometric verification confidence (0.00 to 1.00)'),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_verification', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='match_status',
            field=models.CharField(choices=[('MATCH', 'Match Confirmed'), ('MISMATCH', 'Face Discrepancy / Mismatch'), ('MANUAL_REVIEW', 'Manual Review Required'), ('NO_FACE', 'No Face Detected'), ('MULTI_FACE', 'Multiple Faces Detected in Document'), ('POOR_QUALITY', 'Poor Face Quality / Unusable')], default='MANUAL_REVIEW', help_text='Verification determination status (MATCH, MANUAL_REVIEW, MISMATCH, etc.)', max_length=30),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='similarity_score',
            field=models.FloatField(default=0.0, help_text='Cosine similarity score (0.00 to 1.00)'),
        ),
    ]
