# Generated by Django 6.1.1 on 2026-09-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_verification', '0002_faceverification_document_face_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverification',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Transparent explanation of face comparison or reason for non-applicability'),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='confidence',
            field=models.FloatField(blank=True, default=0.0, help_text='Overall biometric verification confidence (0.00 to 1.00) or null if not applicable', null=True),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='match_status',
            field=models.CharField(choices=[('MATCH', 'Match Confirmed'), ('MISMATCH', 'Face Discrepancy / Mismatch'), ('MANUAL_REVIEW', 'Manual Review Required'), ('NO_FACE', 'No Face Detected'), ('MULTI_FACE', 'Multiple Faces Detected in Document'), ('POOR_QUALITY', 'Poor Face Quality / Unusable'), ('NOT_APPLICABLE', 'Not Applicable (No Document Photo)'), ('NOT_PERFORMED', 'Not Performed'), ('ERROR', 'Processing Error')], default='MANUAL_REVIEW', help_text='Verification determination status (MATCH, MANUAL_REVIEW, NOT_APPLICABLE, etc.)', max_length=30),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='similarity_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Cosine similarity score (0.00 to 1.00) or null if not applicable', null=True),
        ),
    ]
