# Generated by Django 6.1.1 on 2026-09-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_verification', '0003_faceverification_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverification',
            name='liveness_status',
            field=models.CharField(choices=[('PASSED', 'Liveness Passed'), ('FAILED', 'Liveness Failed / Spoof Detected'), ('INCONCLUSIVE', 'Inconclusive Liveness'), ('NOT_APPLICABLE', 'Not Applicable (No Selfie)')], default='PASSED', help_text='Anti-spoofing live selfie assessment (PASSED, FAILED, INCONCLUSIVE, NOT_APPLICABLE)', max_length=30),
        ),
    ]
