# Generated by Django 6.1.1 on 2026-09-26 13:31

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verification_id', models.CharField(db_index=True, help_text='Unique tracking identifier for verification request', max_length=64, unique=True)),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'Permanent Account Number (PAN) Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID (EPIC)'), ('OTHER', 'Other Government Issued ID')], default='OTHER', max_length=30)),
                ('original_file', models.FileField(help_text='Uploaded identity document image or PDF', upload_to=documents.models.document_upload_path)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 cryptographic digest for integrity validation', max_length=64)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Queued for Intake'), ('PROCESSING', 'Screening in Progress'), ('COMPLETED', 'Screening Completed'), ('FAILED', 'Processing Failed'), ('REQUIRES_MANUAL_REVIEW', 'Requires Manual Officer Review')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Document',
                'verbose_name_plural': 'Identity Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
