# Generated by Django 6.1.1 on 2026-09-26 13:37

import documents.models
import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='selfie_file',
            field=models.FileField(blank=True, help_text='Uploaded applicant selfie image (JPG, PNG)', null=True, upload_to=documents.models.selfie_upload_path, validators=[documents.validators.validate_uploaded_selfie]),
        ),
        migrations.AddField(
            model_name='document',
            name='selfie_hash',
            field=models.CharField(blank=True, help_text='SHA-256 cryptographic digest of applicant selfie', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 cryptographic digest of document for tamper validation', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(help_text='Uploaded identity document (JPG, PNG, PDF)', upload_to=documents.models.document_upload_path, validators=[documents.validators.validate_uploaded_document]),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('MANUAL_REVIEW', 'Manual Review')], default='UPLOADED', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='verification_id',
            field=models.CharField(blank=True, db_index=True, help_text='Institutional tracking identifier (e.g. VX-2026-000001)', max_length=64, unique=True),
        ),
    ]
