# Generated by Django 6.1.1 on 2026-09-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_selfie_file_document_selfie_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentQualityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_type', models.CharField(default='unknown_document', help_text='Classified document category (e.g. sample_identity_card, sample_pan_document, etc.)', max_length=50)),
                ('classification_confidence', models.FloatField(default=0.5, help_text='Classifier confidence probability (0.0 to 1.0)')),
                ('quality_score', models.IntegerField(default=100, help_text='Composite document quality score (0 to 100)')),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of detected quality issues (blur, glare, skew, low res)')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='List of passed verification criteria')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Underlying numeric metrics: blur, brightness, contrast, skew, resolution')),
                ('is_poor_quality', models.BooleanField(default=False, help_text='Flag indicating whether document quality mandates manual officer review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_analysis', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Quality Analysis',
                'verbose_name_plural': 'Document Quality Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
