# Generated by Django 6.1.1 on 2026-09-28 06:17

import documents.models
import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentqualityanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(help_text='Uploaded identity document (JPG, JPEG, PNG, WEBP, PDF)', upload_to=documents.models.document_upload_path, validators=[documents.validators.validate_uploaded_document]),
        ),
        migrations.AlterField(
            model_name='document',
            name='selfie_file',
            field=models.FileField(blank=True, help_text='Uploaded applicant selfie image (JPG, JPEG, PNG, WEBP)', null=True, upload_to=documents.models.selfie_upload_path, validators=[documents.validators.validate_uploaded_selfie]),
        ),
    ]
