# Generated by Django 6.1.1 on 2026-09-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is a demo/test screening entry'),
        ),
    ]
