# Generated by Django 6.1.1 on 2026-09-26 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DOCUMENT_UPLOAD', 'Document Uploaded'), ('AI_SCREENING_EXECUTED', 'AI Screening Executed'), ('MANUAL_OFFICER_REVIEW', 'Manual Officer Review'), ('STATUS_UPDATED', 'Verification Status Updated'), ('REPORT_EXPORTED', 'Forensic Report Exported'), ('USER_AUTHENTICATION', 'User Authentication Event')], default='AI_SCREENING_EXECUTED', help_text='Standardized audit action code', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured contextual metadata (IP, user agent, changes, scores)')),
                ('document', models.ForeignKey(blank=True, help_text='Associated document if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.document')),
                ('user', models.ForeignKey(blank=True, help_text='User/Officer responsible for the action (or null for automated system tasks)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
