# Generated by Django 6.1.1 on 2026-09-26 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Originating IPv4 or IPv6 client address', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='verification_id',
            field=models.CharField(blank=True, db_index=True, help_text='Direct tracking ID for indexed lookup', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('DOCUMENT_UPLOAD', 'USER uploaded document'), ('VERIFICATION_START', 'USER started verification'), ('AI_SCREENING_EXECUTED', 'AI analysis completed'), ('CASE_OPENED', 'Reviewer opened case'), ('MANUAL_OFFICER_REVIEW', 'Reviewer marked case for manual review'), ('REVIEW_NOTE_ADDED', 'Reviewer added review notes'), ('STATUS_UPDATED', 'Verification status updated'), ('DOCUMENT_ACCESSED', 'Document accessed'), ('UNAUTHORIZED_ACCESS_ATTEMPT', 'Unauthorized access attempted'), ('REPORT_EXPORTED', 'Forensic report exported'), ('USER_AUTHENTICATION', 'User authentication event')], default='AI_SCREENING_EXECUTED', help_text='Standardized audit action code', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User/Officer responsible for the action (or null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
