# Generated by Django 6.1.1 on 2026-09-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(help_text='Name of the risk factor (e.g., Font Inconsistency, Low Face Similarity, ELA Variance)', max_length=150)),
                ('factor_value', models.CharField(help_text='Measured factor value or detection metric', max_length=255)),
                ('contribution', models.FloatField(default=0.0, help_text='Contribution weight to the total risk score (percentage or points)')),
                ('description', models.TextField(blank=True, help_text='Human-readable explanation of why this factor was triggered')),
                ('verification_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='identity_verification.verificationresult')),
            ],
            options={
                'verbose_name': 'Risk Factor',
                'verbose_name_plural': 'Risk Factors',
                'ordering': ['-contribution'],
            },
        ),
    ]
